[build]
  command = "npm run build"
  functions = "functions"

[build.environment]
  PRISMA_CLIENT_ENGINE_TYPE = "binary"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[plugins.inputs]
  included_files = ["node_modules/.prisma/client/**", "prisma/schema.prisma"]

[functions]
  node_bundler = "esbuild"