openapi: 3.0.0
info:
  title: API GraphQL Fastify
  version: 1.0.0
  description: |
    Documentación de la API GraphQL. Incluye ejemplo de Mutation `registerUsuario`.
servers:
  - url: http://localhost:3000/graphql
paths:
  /graphql:
    post:
      summary: Endpoint GraphQL
      description: |
        Endpoint único para consultas y mutaciones GraphQL.
        
        ### Ejemplo de Mutation: registerUsuario
        ```graphql
        mutation {
          registerUsuario(
            token: "string",
            name: "Nombre",
            email: "correo@ejemplo.com",
            password: "123456",
            rol: ADMIN
          ) {
            type
            message
            data {
              id
              name
              email
              rol
              token
            }
          }
        }
        ```
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  example: |
                    mutation {
                      registerUsuario(
                        token: "string",
                        name: "Nombre",
                        email: "correo@ejemplo.com",
                        password: "123456",
                        rol: ADMIN
                      ) {
                        type
                        message
                        data {
                          id
                          name
                          email
                          rol
                          token
                        }
                      }
                    }
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      registerUsuario:
                        type: object
                        properties:
                          type:
                            type: string
                          message:
                            type: string
                          data:
                            type: object
                            properties:
                              id:
                                type: integer
                              name:
                                type: string
                              email:
                                type: string
                              rol:
                                type: string
                              token:
                                type: string
